# 3CNN model configuration
model_name: multi_stft_cnn
sample_rate: 22050
n_mels: 64
hop_length: 512
batch_size: 16  # Smaller batch size due to higher memory requirements
num_epochs: 15
learning_rate: 2e-4  # Adjusted learning rate for 3CNN
num_workers: 2
n_branches: 3  # Number of branches in the 3CNN model
branch_output_dim: 128  # Output dimension of each branch

# Training efficiency settings
limit_val_batches: 1  # Use only 10% of validation data for faster training (1.0 = 100%)
num_sanity_val_steps: 2  # Reduce sanity validation steps for faster startup

# Dataset creation settings
max_original_samples: null  # Use all original samples
original_data_percentage: 1  # Use all original IRMAS data

# Training dataset settings
max_samples: null  # Maximum samples to use for training (None for all)
max_test_samples: null # Maximum samples to use for testing (None for all)