# 9CNN model configuration
model_name: wavelet_cnn
sample_rate: 22050
n_mels: 64
hop_length: 512
batch_size: 32  # Smaller batch size due to higher memory requirements
num_epochs: 1
learning_rate: 2e-4  # Adjusted learning rate for 9CNN
num_workers: 2

# Training efficiency settings
limit_val_batches: 0.1  # Use only 10% of validation data for faster training (1.0 = 100%)
num_sanity_val_steps: 2  # Reduce sanity validation steps for faster startup

# Dataset creation settings
max_original_samples: 50  # Limit original samples to avoid memory issues
num_mixtures: 5  # Create 5 synthetic mixtures
min_instruments: 1  # Minimum instruments per mixture
max_instruments: 2  # Maximum instruments per mixture
original_data_percentage: 0.1  # Use only 10% of original IRMAS data for preprocessing

# Training dataset settings
max_samples: 50  # Maximum samples to use for training (None for all)