# PANNs-enhanced model configuration
model_name: panns_enhanced
sample_rate: 22050
n_mels: 64
hop_length: 512
batch_size: 32  # Increased batch size for better gradient estimates
num_epochs: 50  # Extended training time to allow convergence
num_workers: 2  # Increased for faster data loading
weight_decay: 2e-4  # Stronger regularization

# PANNs-specific settings
freeze_epochs: 2  # Initial epochs with frozen backbone
frozen_learning_rate: 0.002  # Higher LR when backbone frozen
finetune_learning_rate: 0.0003  # Increased LR for fine-tuning
use_lr_scheduler: true  # Enable learning rate scheduler
lr_scheduler_patience: 3  # Wait this many epochs before reducing LR
lr_scheduler_factor: 0.5  # Multiply LR by this factor when plateau occurs

# Training efficiency settings
limit_val_batches: 1.0  # Use all validation data for reliable metrics
num_sanity_val_steps: 2  # Reduce sanity validation steps for faster startup

# Data augmentation settings
mixup_alpha: 0.2  # Mixup interpolation strength (0 disables mixup)

# Dataset creation settings
max_original_samples: null  # Use all original samples
num_mixtures: 0  # Create synthetic mixtures
min_instruments: 1  # Minimum instruments per mixture
max_instruments: 2  # Maximum instruments per mixture
original_data_percentage: 1  # Use all original IRMAS data

# Training dataset settings
max_samples: null  # Maximum samples to use for training (None for all)
max_test_samples: null