# PANNs-enhanced model configuration
model_name: panns_enhanced
sample_rate: 22050
n_mels: 64
hop_length: 512
batch_size: 32  # Smaller batch size due to larger model
num_workers: 2

# PANNs-specific settings
frozen_learning_rate: 0.003  # Higher LR when backbone frozen
finetune_learning_rate: 0.0002  # Adjusted LR for fine-tuning
learning_rate: 0.0002

# Training efficiency settings
num_sanity_val_steps: 2  # Reduce sanity validation steps for faster startup

# Dataset creation settings
num_mixtures: 0  # Create synthetic mixtures
min_instruments: 1  # Minimum instruments per mixture
max_instruments: 2  # Maximum instruments per mixture

# Training dataset settings
num_epochs: 2  # Extended for two-phase training, for fast run: 2
freeze_epochs: 1  # Increased initial epochs with frozen backbone, for fast run: 1
limit_val_batches: 0.2  # Use all validation data for reliable metrics, for fast run: 0.2
original_data_percentage: 0.1  # Use all original IRMAS data, for fast run: 0.1
max_original_samples: 20  # Use all original samples, for fast run: 20
max_samples: 20  # Maximum samples to use for training (None for all), for fast run: 20
max_test_samples: 20 # Maximum samples to use for testing (None for all), for fast run: 20
num_scales: 256

s_min_samples: 2.0
s_max_samples: 512.0
morlet_w0: 6.0
morlet_support: 6.0
max_duration_sec: 6.0   # trim/pad for speed (optional)
peak_normalize: true